In [1]:
from sklearn.model_selection import TimeSeriesSplit
import numpy as np
X=np.array([[10,20],[30,40],[50,60],[20,50],[10,30]])
y=np.array([100,200,300,400,500,600])
tscv =TimeSeriesSplit(n_splits=4)

for train_index, test_index in tscv.split(X):
    print("TRAIN:",train_index, "TEST:", test_index)
    
    #to get the indices
    X_train, X_test =X[train_index],X[test_index]
    y_train, y_test =y[train_index],y[test_index]
    print(X_train, y_train)

TRAIN: [0] TEST: [1]
[[10 20]] [100]
TRAIN: [0 1] TEST: [2]
[[10 20]
 [30 40]] [100 200]
TRAIN: [0 1 2] TEST: [3]
[[10 20]
 [30 40]
 [50 60]] [100 200 300]
TRAIN: [0 1 2 3] TEST: [4]
[[10 20]
 [30 40]
 [50 60]
 [20 50]] [100 200 300 400]
